version: '3'
networks:
  laravel:
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
  php:
    networks:
      -laravel
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
  mysql:
    image: mysql:5.7.22
    container_name: my_sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todoapp
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
  cache:
    image: memcached:1.6-alpine
